version: "3.9"
   
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
  gateway:
    build:
      context: https://github.com/mkm29/go-grp-api-gateway.git
    ports:
      - "3000:3000"
  auth:
    build:
      context: https://github.com/mkm29/go-grpc-auth-svc.git
      args:
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
    ports:
      - "50051:50051"
    depends_on:
      - db
  order:
    build:
      context: https://github.com/mkm29/go-grpc-order-svc.git
      args:
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
    ports:
      - "50053:50053"
    depends_on:
      - db
  product:
    build:
      context: https://github.com/mkm29/go-grpc-product-svc.git
      args:
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
    ports:
      - "50052:50052"
    depends_on:
      - db