version: "3.9"
   
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
  gateway:
    image: mkm29/grpc-api-gateway:0.1.1
    ports:
      - "3000:3000"
  auth:
    build:
      context: ../go-grpc-auth-svc/
      args:
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
    ports:
      - "50051:50051"
    depends_on:
      - db
  order:
    build:
      context: ../go-grpc-order-svc/
      args:
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
    ports:
      - "50053:50053"
    depends_on:
      - db
  product:
    build:
      context: ../go-grpc-product-svc/
      args:
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
    ports:
      - "50052:50052"
    depends_on:
      - db