version: "3.9"
   
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
  gateway:
    image: mkm29/grpc-api-gateway:0.1.1
    ports:
      - "3000:3000"
  auth:
    image: mkm29/grpc-auth-svc:0.1.1
    ports:
      - "50051:50051"
    depends_on:
      - db
  order:
    image: mkm29/grpc-order-svc:0.1.2
    ports:
      - "50053:50053"
    depends_on:
      - db
  product:
    image: mkm29/grpc-product-svc:0.1.1
    ports:
      - "50052:50052"
    depends_on:
      - db